import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {transform} from 'esbuild';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
let html=await readFile(path.join(root,'src/index.html'),'utf8');
const match=html.match(/<script type="text\/babel"[^>]*>([\s\S]*?)<\/script>/);
if(!match)throw new Error('Missing canonical JSX source in src/index.html');
let jsx=match[1].replace(/@import url\('https:\/\/fonts\.googleapis\.com\/css2\?[^']+'\);/g,'');
const result=await transform(jsx,{loader:'jsx',jsx:'transform',jsxFactory:'React.createElement',jsxFragment:'React.Fragment',target:'es2020',minify:true,legalComments:'inline',charset:'utf8',sourcefile:'phaser-app.jsx'});
const digest=createHash('sha256').update(result.code).digest('hex').slice(0,12);
const appFile=`assets/app.${digest}.min.js`;
html=html.replace(match[0],`<script defer src="${appFile}"></script>`);
html=html.replace(/  <script src="https:\/\/accounts\.google\.com\/gsi\/client" async defer><\/script>\n/,'');
const start=html.indexOf('  <!-- După #root:');
const end=html.indexOf('<script defer src="assets/app.',start);
if(start<0||end<0)throw new Error('Missing startup bounds');
html=html.slice(0,start)+`  <script defer src="assets/vendor/react-18.3.1.js"></script>
  <script defer src="assets/vendor/react-dom-18.3.1.js"></script>
  <script defer src="assets/vendor/supabase-2.116.0.js"></script>
  `+html.slice(end);
html=html.replace('<title>Phaser Manager</title>',`<title>Phaser Manager</title>
  <!-- Generated by npm run build from src/index.html. Do not edit this file directly. -->
  <meta name="phaser-build" content="${digest}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap">`);
html=html.replace('Dacă rămâne negru, deschide http://localhost:8080','');
const htmlPath=path.join(root,'index.html');const appPath=path.join(root,appFile);
if(process.argv.includes('--check')){
 if(await readFile(htmlPath,'utf8')!==html||await readFile(appPath,'utf8')!==result.code)throw new Error('Generated files are stale; run npm run build.');
}else{
 await mkdir(path.join(root,'assets'),{recursive:true});
 await writeFile(appPath,result.code);await writeFile(htmlPath,html);
}
console.log(JSON.stringify({appFile,htmlBytes:Buffer.byteLength(html),appBytes:Buffer.byteLength(result.code)}));
